version: '3.7'

services:
  # 명칭 설정
  start-react-front:
    environment:
      # 시간 설정
      TZ: "Asia/Seoul"
    # docker container 이름 설정
    container_name: start-react-front
    # docker image 이름 설정
    image: start-react-front-image
    build:
      context: .
      # 빌드시 사용할 docker 파일 설정
      dockerfile: ./Dockerfile
    ports:
      # 외부 포트 : 내부포트
      - 8081:3000


volumes:
  data:
    driver: local
# 추가 네트워크 설정
networks:
  default:
    external: 
      name: dizzy